language: python
matrix:
  include:
  - os: linux
    python: 2.7
  - os: osx
    language: generic
sudo: required
services:
  - docker
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - pip install -U pip pytest
install:
  - pip install -r requirements.txt
script:
  - echo "Running custom build scripts..."
  - echo "TRAVIS_BUILD_DIR = ${TRAVIS_BUILD_DIR}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./docker-build.sh; fi
  - PYTHONPATH=src/main/python pytest src/test/python
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then APTLY_VERSION=0.9.7 ./itest.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then APTLY_VERSION=1.1.1 ./itest.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then APTLY_VERSION=1.2.0 ./itest.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -allowUntrusted -verboseR -pkg "${TRAVIS_BUILD_DIR}"/build/com.a4pizza.raptly.pkg -target / ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then raptly; fi
deploy:
  - provider: releases
    api_key:
      secure: QEm1RJNgGbRMbKyYG+WxkZjbEhQt8+LKM/fcZCiO0jvCfyPFmMMTH2ZuzG2L6GeVJdgyUT6Z0ewrSlJcuDefXvFT374YlOMFqVLb9yK4iHa1Jd3I9pJ0fqFEf0uBPOnYZs5+gn55Yxc3szsEIt282CAmo3E8lIojX0XoLHNSWtvTfCCIc1sneiUqUv914BJs3Mwg/t859oDarJU+mWAadgJUXf4bhMsyO7/XQhBK4YQsmzv7xDutUtEN9711q1rVVdnqPE1GGkb7nzkNSrs92NZZLYerUHxPELL2tfWeqtIRjo2/+Rvz6wEkP0FC4AmWr+JtR3uxjJq9vZpZNRpZVRTsJ3MIvbIf9JoEEYca6s4XwXgq0q36dBy9++Kj7NKm4jLc2NJLZqM/QZf+HNec0VmtE8InFwhWv9pXSN9c0Wr9G9Nl9xghS/0XA9jJHHx8T1U0qxxb9bjzk7mRMTXGTSxKVKuicyKJLrF0qU7ubkhHWpPH3qLGO4/NUs636EYY0YR6znSTTWeIeZkQZMdDhSCQGrbSQk5g2qNKOXrpR6akPj9rJFTI0KOka4C7OgWjuGfACBkdEsp8QiSqLOsFcjJfabDL+3iRfhmBuK3Y6pylbFXfmuSx1w/vQWmEkb74HQzTBDxC9e0iusViVyoM/S64L+TQ2fuohKS+jc5Cxww=
    file: ${TRAVIS_BUILD_DIR}/build/com.a4pizza.raptly.pkg
    skip_cleanup: true
    on:
      repo: a4pizza/test1
      tags: true
      condition: "$TRAVIS_OS_NAME == osx"
  - provider: releases
    api_key:
      secure: QEm1RJNgGbRMbKyYG+WxkZjbEhQt8+LKM/fcZCiO0jvCfyPFmMMTH2ZuzG2L6GeVJdgyUT6Z0ewrSlJcuDefXvFT374YlOMFqVLb9yK4iHa1Jd3I9pJ0fqFEf0uBPOnYZs5+gn55Yxc3szsEIt282CAmo3E8lIojX0XoLHNSWtvTfCCIc1sneiUqUv914BJs3Mwg/t859oDarJU+mWAadgJUXf4bhMsyO7/XQhBK4YQsmzv7xDutUtEN9711q1rVVdnqPE1GGkb7nzkNSrs92NZZLYerUHxPELL2tfWeqtIRjo2/+Rvz6wEkP0FC4AmWr+JtR3uxjJq9vZpZNRpZVRTsJ3MIvbIf9JoEEYca6s4XwXgq0q36dBy9++Kj7NKm4jLc2NJLZqM/QZf+HNec0VmtE8InFwhWv9pXSN9c0Wr9G9Nl9xghS/0XA9jJHHx8T1U0qxxb9bjzk7mRMTXGTSxKVKuicyKJLrF0qU7ubkhHWpPH3qLGO4/NUs636EYY0YR6znSTTWeIeZkQZMdDhSCQGrbSQk5g2qNKOXrpR6akPj9rJFTI0KOka4C7OgWjuGfACBkdEsp8QiSqLOsFcjJfabDL+3iRfhmBuK3Y6pylbFXfmuSx1w/vQWmEkb74HQzTBDxC9e0iusViVyoM/S64L+TQ2fuohKS+jc5Cxww=
    file_glob: true
    file: ${TRAVIS_BUILD_DIR}/build/raptly_*.*.*_all.deb
    skip_cleanup: true
    on:
      repo: a4pizza/test1
      tags: true
      condition: "$TRAVIS_OS_NAME == linux"

