language: python

matrix:
    include:
        # Use built in venv for linux
        - os: linux
          python: 2.7
        # Use generic for OSX
        - os: osx
          language: generic
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - pip install -U pip pytest
install: 
  - pip install -r requirements.txt
# command to run tests
script: 
  - PYTHONPATH=src/main/python pytest
