language: python
os:
  - osx
  - linux
before_install:
  - pip install -U pip pytest
install: 
  - pip install -r requirements.txt
# command to run tests
script: 
  - PYTHONPATH=src/main/python pytest
